from __future__ import annotations

from collections.abc import Iterator, Mapping
from typing import Any, Dict, List, Optional

from game.content.story_nodes_act1 import STORY_NODES_ACT1
from game.content.story_nodes_act2 import STORY_NODES_ACT2
from game.content.story_nodes_act3 import STORY_NODES_ACT3
from game.content.story_nodes_intro import STORY_NODES_INTRO
from game.content.story_utils import simplify_story_nodes

_RAW_STORY_NODES: Dict[str, Dict[str, Any]] = {
    **STORY_NODES_INTRO,
    **STORY_NODES_ACT1,
    **STORY_NODES_ACT2,
    **STORY_NODES_ACT3,
}

_CACHED_STORY_NODES: Optional[Dict[str, Dict[str, Any]]] = None
_CACHED_SIMPLIFICATION_REPORT: tuple[str, ...] = ()


def get_choice_simplification_report() -> tuple[str, ...]:
    """Return the report generated by the story simplification pass."""
    init_story_nodes()
    return _CACHED_SIMPLIFICATION_REPORT


def init_story_nodes() -> None:
    """Build the simplified story graph once (no mutation of the raw story dict)."""
    global _CACHED_STORY_NODES, _CACHED_SIMPLIFICATION_REPORT
    if _CACHED_STORY_NODES is not None:
        return
    nodes, report = simplify_story_nodes(_RAW_STORY_NODES)
    _CACHED_STORY_NODES = nodes
    _CACHED_SIMPLIFICATION_REPORT = tuple(report)


def _get_story_nodes_cached() -> Dict[str, Dict[str, Any]]:
    init_story_nodes()
    assert _CACHED_STORY_NODES is not None
    return _CACHED_STORY_NODES


class _LazyStoryNodes(Mapping[str, Dict[str, Any]]):
    """Mapping facade that lazily initializes the simplified story graph on first access.

    This keeps call sites ergonomic (`STORY_NODES[...]`, `STORY_NODES.items()`), while
    ensuring we don't mutate a module-level dict in-place during simplification.
    """

    def __getitem__(self, key: str) -> Dict[str, Any]:
        return _get_story_nodes_cached()[key]

    def __iter__(self) -> Iterator[str]:
        return iter(_get_story_nodes_cached())

    def __len__(self) -> int:
        return len(_get_story_nodes_cached())

    def get(self, key: str, default: Any = None) -> Any:
        return _get_story_nodes_cached().get(key, default)

    def items(self):
        return _get_story_nodes_cached().items()

    def keys(self):
        return _get_story_nodes_cached().keys()

    def values(self):
        return _get_story_nodes_cached().values()

    def __contains__(self, key: object) -> bool:
        return key in _get_story_nodes_cached()


# Public, import-friendly mapping used everywhere else in the app.
STORY_NODES: Mapping[str, Dict[str, Any]] = _LazyStoryNodes()

